---
name: PIP Instance Requirements
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]

    steps:
      - uses: actions/checkout@v2
        with:
          path: ./
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/requirements.txt ]; then python -m pip install -r requirements/requirements.txt; fi
